name: Java CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dockerproxy.repos.tech.orange/maven:3.9.7-eclipse-temurin-21
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify Java & Maven
        run: |
          java -version
          mvn -version

      - name: Build project
        run: mvn compile
        continue-on-error: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/